# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib smotifrs, .registration = TRUE
NULL

#' Internal smoke-test entry point used during package build.
#'
#' @keywords internal
hello_world <- function() .Call(wrap__hello_world)

#' Internal FFI: find motifs from R-supplied vectors. Use the
#' user-facing [`find_motifs_rs()`] wrapper instead.
#'
#' @keywords internal
rs_find_motifs <- function(cell_ids, cell_types, edge_source, edge_target, size, colored, anchored_on) .Call(wrap__rs_find_motifs, cell_ids, cell_types, edge_source, edge_target, size, colored, anchored_on)

#' Internal FFI: read nodes/edges parquet directly in Rust and find
#' motifs. Use the user-facing [`find_motifs_from_parquet()`] wrapper.
#'
#' @keywords internal
rs_find_motifs_from_parquet <- function(nodes_path, edges_path, size, colored, anchored_on_idx) .Call(wrap__rs_find_motifs_from_parquet, nodes_path, edges_path, size, colored, anchored_on_idx)

# nolint end
